from __future__ import annotations

import asyncio
import hashlib
import os
import shutil
import tempfile
from datetime import datetime, timezone
from uuid import uuid4

from episode.domain.models import RawArtifact


def ensure_dir(path: str) -> str:
    os.makedirs(path, exist_ok=True)
    return path


def available_destination(path: str) -> str:
    """Avoid overwriting immutable evidence when a device reuses a filename."""
    if not os.path.exists(path):
        return path
    stem, extension = os.path.splitext(path)
    return f"{stem}_{str(uuid4())[:8]}{extension}"


def save_payload(
    evidence_root: str,
    subdir: str,
    data: bytes,
    prefix: str = "payload",
) -> str:
    return save_bytes(evidence_root, subdir, data, prefix=prefix, extension=".xml")


def save_bytes(
    evidence_root: str,
    subdir: str,
    data: bytes,
    *,
    prefix: str = "artifact",
    extension: str = "",
) -> str:
    ts = datetime.now(tz=timezone.utc).strftime("%Y%m%d_%H%M%S_%f")
    dest = ensure_dir(os.path.join(evidence_root, subdir))
    filename = f"{prefix}_{ts}_{str(uuid4())[:8]}{extension}"
    path = os.path.join(dest, filename)
    descriptor, temporary_path = tempfile.mkstemp(
        dir=dest,
        prefix=".episode-write-",
        suffix=".tmp",
    )
    try:
        with os.fdopen(descriptor, "wb") as file:
            file.write(data)
            file.flush()
            os.fsync(file.fileno())
        os.replace(temporary_path, path)
    finally:
        if os.path.exists(temporary_path):
            os.unlink(temporary_path)
    seal_file(path)
    return path


def move_snapshot(
    evidence_root: str,
    src_path: str,
    subdir: str = "snapshots",
) -> str:
    dest = ensure_dir(os.path.join(evidence_root, subdir))
    filename = os.path.basename(src_path)
    dest_path = available_destination(os.path.join(dest, filename))
    shutil.move(src_path, dest_path)
    seal_file(dest_path)
    return dest_path


def sha256_file(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def seal_file(path: str) -> None:
    """Best-effort write protection for bytes received or generated by Episode."""
    try:
        mode = os.stat(path).st_mode
        os.chmod(path, mode & ~0o222)
    except OSError:
        # Checksums remain the portable integrity control on filesystems where
        # permissions cannot be changed (for example some network mounts).
        pass


def describe_artifact(
    path: str,
    artifact_type: str,
    mime_type: str,
    *,
    original_filename: str | None = None,
    metadata: dict | None = None,
    seal: bool = True,
) -> RawArtifact:
    byte_size = os.path.getsize(path)
    checksum = sha256_file(path)
    if seal:
        seal_file(path)
    return RawArtifact(
        artifact_type=artifact_type,
        file_path=path,
        mime_type=mime_type,
        byte_size=byte_size,
        sha256=checksum,
        original_filename=original_filename or os.path.basename(path),
        sealed=seal,
        metadata=metadata or {},
    )


def move_to_episode(
    data_root: str,
    episode_id: str,
    current_path: str,
    subdir: str,
) -> str:
    if not current_path or not os.path.exists(current_path):
        return current_path
    episode_dir = os.path.join(data_root, "episodes", episode_id, subdir)
    os.makedirs(episode_dir, exist_ok=True)
    filename = os.path.basename(current_path)
    dest = os.path.join(episode_dir, filename)
    if os.path.normpath(current_path) != os.path.normpath(dest):
        dest = available_destination(dest)
        shutil.move(current_path, dest)
    return dest


async def async_move_to_episode(
    data_root: str,
    episode_id: str,
    current_path: str,
    subdir: str,
) -> str:
    return await asyncio.to_thread(move_to_episode, data_root, episode_id, current_path, subdir)
